
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "NativeCalculatorModule.h"
#include "AppTurboModuleProvider.h"

namespace facebook
{
  namespace react
  {

    std::shared_ptr<TurboModule> NativeCalculatorModule_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params)
    {
      static facebook::react::AppTurboModuleProvider appTurboModuleProvider;
      return appTurboModuleProvider.getTurboModule(moduleName, params.jsInvoker);
    }

  } // namespace react
} // namespace facebook
